import { Geist, Geist_Mono } from "next/font/google";
import { Lobster_Two } from "next/font/google";
import SocialButtons from "@/components/SocialButtons"
import "./globals.css";

const lobster = Lobster_Two({
  variable: "--font-lobster",
  subsets: ["latin"],
  weight: ["400", "700"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Solpiene",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-x-hidden w-lvw bg-[#F5F1EA]`}
      >
        <SocialButtons/>
        {children}
      </body>
    </html>
  );
}
